version: '3'

services:
  server:
    image: zilliz/infini-webserver:0.1.0-d101501
    expose:
      - ${API_SERVER_PORT}
    environment:
      API_SERVER_PORT: ${API_SERVER_PORT}
      MEGAWISE_HOST: ${MEGAWISE_HOST}
      SESSION_EXPIRES: ${SESSION_EXPIRES}
      MEGAWISE_USER: ${MEGAWISE_USER}
      MEGAWISE_PWD: ${MEGAWISE_PWD}
      MEGAWISE_DB: ${MEGAWISE_DB}
      MEGAWISE_PORT: ${MEGAWISE_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}

  client:
    image: zilliz/infini-webclient:0.1.0-d101501
    environment:
      API_URL: ${API_URL}
    expose:
      - ${LOCAL_PORT}
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}
    links:
      - server